# Edit this Gemfile to bundle your application's dependencies.
source 'http://gemcutter.org'
group :development, :test do
  gem "rails", "~> 7.0.8", ">= 7.0.8.1"
  gem 'rspec-rails', '~> 2.13', '>= 2.13.1'
end
