# Edit this Gemfile to bundle your application's dependencies.
source 'http://gemcutter.org'
group :development, :test do
  gem "rails", "~> 6.1.7", ">= 6.1.7.3"
  gem 'rspec-rails', '~> 2.13', '>= 2.13.0'
end
